In [1]:
import numpy as np

In [6]:
my_list = [1,2,3,4]

In [3]:
my_array = np.array(my_list)

In [4]:
my_array

array([1, 2, 3, 4])

In [5]:
my_array.shape

(4,)

In [7]:
my_array.dtype

dtype('int32')

In [12]:
np.zeros((2,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [13]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [15]:
np.ones((2,1))

array([[1.],
       [1.]])