In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
np.where(arr>8,2,arr)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 2]])

In [4]:
normal_array = np.random.randn(5)
normal_array

array([ 0.30575531,  0.67782405, -2.05149703,  1.35739796, -1.17220516])

In [6]:
normal_array1 = np.random.randn(5,10)

In [7]:
normal_array1

array([[ 1.66155664,  0.61767196,  0.67337107, -1.19696287, -0.68456326,
         1.41561267, -1.29027736, -0.32616036,  0.02852962,  0.03916853],
       [ 0.08743313, -1.34594521, -0.49048844, -0.16778638, -0.01809848,
        -0.59565519,  0.50872867, -0.64492201,  1.63726662, -0.61688411],
       [-0.5530974 , -0.68571304, -1.01447966, -1.11795323, -0.882644  ,
        -0.31767828, -0.34858357, -1.75350057, -1.67186734, -0.63777753],
       [ 0.0919323 , -1.58780923,  0.12800433, -0.03777333,  0.28019805,
         0.65278952,  0.12812097,  0.7414024 , -0.30388481,  0.46969917],
       [ 1.19903771,  1.62767819,  1.86210556,  2.21126559,  1.03744948,
        -0.85314854, -0.57520744, -0.95214519,  0.4947444 , -0.10689344]])

In [8]:
normal_array1.sum()

-3.184133660027273

In [11]:
arr.sum(1)

array([ 6, 15, 24])

In [12]:
arr.mean()

5.0

In [13]:
arr.mean(0)

array([4., 5., 6.])