In [1]:
import numpy as np

In [2]:
arr = np.arange(40)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [10]:
arr = arr.reshape((8,5))

reshape can be done as multiples of the range specified i.e 40 = 10*4 or 4*10 or 8*5 or 5*8

In [12]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [13]:
arr.T

array([[ 0,  5, 10, 15, 20, 25, 30, 35],
       [ 1,  6, 11, 16, 21, 26, 31, 36],
       [ 2,  7, 12, 17, 22, 27, 32, 37],
       [ 3,  8, 13, 18, 23, 28, 33, 38],
       [ 4,  9, 14, 19, 24, 29, 34, 39]])

also we can do dot product of arrays

In [14]:
np.dot(arr,arr.T)

array([[  30,   80,  130,  180,  230,  280,  330,  380],
       [  80,  255,  430,  605,  780,  955, 1130, 1305],
       [ 130,  430,  730, 1030, 1330, 1630, 1930, 2230],
       [ 180,  605, 1030, 1455, 1880, 2305, 2730, 3155],
       [ 230,  780, 1330, 1880, 2430, 2980, 3530, 4080],
       [ 280,  955, 1630, 2305, 2980, 3655, 4330, 5005],
       [ 330, 1130, 1930, 2730, 3530, 4330, 5130, 5930],
       [ 380, 1305, 2230, 3155, 4080, 5005, 5930, 6855]])

In [16]:
arr.swapaxes(0,1)

array([[ 0,  5, 10, 15, 20, 25, 30, 35],
       [ 1,  6, 11, 16, 21, 26, 31, 36],
       [ 2,  7, 12, 17, 22, 27, 32, 37],
       [ 3,  8, 13, 18, 23, 28, 33, 38],
       [ 4,  9, 14, 19, 24, 29, 34, 39]])