In [1]:
import numpy as np

In [3]:
arr1 = np.array([[1,2,3],[7,8,9]])
arr2 = np.array([[4,5,6],[10,11,12]])
arr1

array([[1, 2, 3],
       [7, 8, 9]])

In [4]:
arr2

array([[ 4,  5,  6],
       [10, 11, 12]])

# output and load single arrays

In [5]:
np.save('myarray',arr1)

In [6]:
np.load('myarray.npy')

array([[1, 2, 3],
       [7, 8, 9]])

# output and load multiple arrays

In [7]:
np.savez('myarrays.npz',x=arr1,y=arr2)

In [8]:
arrays = np.load('myarrays.npz')

In [9]:
arrays['x']

array([[1, 2, 3],
       [7, 8, 9]])

In [10]:
arrays['y']

array([[ 4,  5,  6],
       [10, 11, 12]])

# output and load arrays into text files

In [11]:
np.savetxt('mytextarray.txt',arr1,delimiter=',')

In [13]:
np.loadtxt('mytextarray.txt',delimiter=',')

array([[1., 2., 3.],
       [7., 8., 9.]])