In [1]:
import numpy as np
import pandas as pd
from numpy.random import randn
from pandas import Series,DataFrame

# concatenate in numpy

In [2]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
np.concatenate([arr1,arr1]) # default axis = 0 i.e index wise

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
np.concatenate([arr1,arr1],axis=1) # column wise

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

# concatenate in pandas

In [5]:
ser1 = Series(randn(5),index=['A','B','C','D','E'])
ser1

A    0.099430
B    1.706234
C    0.550555
D   -1.396472
E   -1.306641
dtype: float64

In [7]:
ser2 = Series(randn(3),index=['E','F','G'])
ser2

E   -0.328608
F   -0.714351
G   -0.180004
dtype: float64

In [8]:
pd.concat([ser1,ser2]) # default axis=0 i.e index wise

A    0.099430
B    1.706234
C    0.550555
D   -1.396472
E   -1.306641
E   -0.328608
F   -0.714351
G   -0.180004
dtype: float64

In [11]:
# we can also assign another index to each of the above series to access the individual series(index hierarchy)
pd.concat([ser1,ser2],keys=['First','Second'])

First   A    0.099430
        B    1.706234
        C    0.550555
        D   -1.396472
        E   -1.306641
Second  E   -0.328608
        F   -0.714351
        G   -0.180004
dtype: float64

In [9]:
pd.concat([ser1,ser2],axis=1) # series side by side concat implies this will result in dataframe**

0         1
A  0.099430       NaN
B  1.706234       NaN
C  0.550555       NaN
D -1.396472       NaN
E -1.306641 -0.328608
F       NaN -0.714351
G       NaN -0.180004

In [12]:
df1 = DataFrame(randn(4,4),columns=['A','B','C','D'])
df1

A         B         C         D
0  2.098433 -0.739029  0.972341  1.042594
1  0.059471 -0.114141 -1.092738 -0.411650
2  2.299899 -2.190326  0.286111 -0.447949
3  0.321039  0.489466  0.563414 -0.652228

In [15]:
df2 = DataFrame(randn(5,5),columns=['D','B','E','F','G'])
df2

D         B         E         F         G
0 -0.547244  0.142348 -1.744574 -0.028811 -1.179137
1 -1.148326  0.141600  0.364796 -1.601593  1.736619
2 -1.829275 -0.140747  0.732179 -1.037417  1.166752
3  1.068884  0.132569  0.777326 -0.713951  0.684661
4 -0.451675 -0.227335  1.136526 -1.660873  0.005942

In [16]:
pd.concat([df1,df2])

A         B         C         D         E         F         G
0  2.098433 -0.739029  0.972341  1.042594       NaN       NaN       NaN
1  0.059471 -0.114141 -1.092738 -0.411650       NaN       NaN       NaN
2  2.299899 -2.190326  0.286111 -0.447949       NaN       NaN       NaN
3  0.321039  0.489466  0.563414 -0.652228       NaN       NaN       NaN
0       NaN  0.142348       NaN -0.547244 -1.744574 -0.028811 -1.179137
1       NaN  0.141600       NaN -1.148326  0.364796 -1.601593  1.736619
2       NaN -0.140747       NaN -1.829275  0.732179 -1.037417  1.166752
3       NaN  0.132569       NaN  1.068884  0.777326 -0.713951  0.684661
4       NaN -0.227335       NaN -0.451675  1.136526 -1.660873  0.005942

In [17]:
pd.concat([df1,df2],ignore_index=True) #follows proper indexing

A         B         C         D         E         F         G
0  2.098433 -0.739029  0.972341  1.042594       NaN       NaN       NaN
1  0.059471 -0.114141 -1.092738 -0.411650       NaN       NaN       NaN
2  2.299899 -2.190326  0.286111 -0.447949       NaN       NaN       NaN
3  0.321039  0.489466  0.563414 -0.652228       NaN       NaN       NaN
4       NaN  0.142348       NaN -0.547244 -1.744574 -0.028811 -1.179137
5       NaN  0.141600       NaN -1.148326  0.364796 -1.601593  1.736619
6       NaN -0.140747       NaN -1.829275  0.732179 -1.037417  1.166752
7       NaN  0.132569       NaN  1.068884  0.777326 -0.713951  0.684661
8       NaN -0.227335       NaN -0.451675  1.136526 -1.660873  0.005942

In [18]:
pd.concat([df1,df2],axis=1)

A         B         C         D         D         B         E  \
0  2.098433 -0.739029  0.972341  1.042594 -0.547244  0.142348 -1.744574   
1  0.059471 -0.114141 -1.092738 -0.411650 -1.148326  0.141600  0.364796   
2  2.299899 -2.190326  0.286111 -0.447949 -1.829275 -0.140747  0.732179   
3  0.321039  0.489466  0.563414 -0.652228  1.068884  0.132569  0.777326   
4       NaN       NaN       NaN       NaN -0.451675 -0.227335  1.136526   

          F         G  
0 -0.028811 -1.179137  
1 -1.601593  1.736619  
2 -1.037417  1.166752  
3 -0.713951  0.684661  
4 -1.660873  0.005942