In [1]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [2]:
arr1 = np.random.permutation(5) # creates a random array of elements from 0 to 4
arr1

array([0, 1, 4, 3, 2])

In [12]:
arr2 = np.random.randint(1,3,20) # creates an array of random numbers within the given range of low and high 
# with repititions till the size we specified.
arr2

array([2, 2, 2, 1, 2, 2, 1, 2, 2, 1, 1, 2, 2, 2, 1, 1, 1, 2, 1, 1])

In [5]:
df1 = DataFrame(np.random.randn(5,4))
df1

0         1         2         3
0  0.923065  0.097195 -1.561360 -0.834299
1  1.192463 -1.901595 -0.440098  0.584312
2 -0.769520  0.820536 -1.066360 -1.465237
3 -2.469124  1.471670 -2.317008 -0.784439
4 -0.197502 -1.355848  0.405733  0.889863

In [6]:
df1.take(arr1) # changes index as per values in arr1

0         1         2         3
0  0.923065  0.097195 -1.561360 -0.834299
1  1.192463 -1.901595 -0.440098  0.584312
4 -0.197502 -1.355848  0.405733  0.889863
3 -2.469124  1.471670 -2.317008 -0.784439
2 -0.769520  0.820536 -1.066360 -1.465237

In [8]:
my_array = np.array([1,2,3])

In [14]:
my_array.take(arr2) # creates another array by applying arr2 on my_array. 
# takes elements from my_array1 based on indicies mentioned in arr2

array([3, 3, 3, 2, 3, 3, 2, 3, 3, 2, 2, 3, 3, 3, 2, 2, 2, 3, 2, 2])